# .github/workflows/pushups.yml
name: Pushcut – hourly 6 a.m.–6 p.m.

on:
  schedule:
    # 06:00-16:00 Pacific (13-23 UTC)
    - cron: '0 13-23 * * *'
    # 17:00-18:00 Pacific (00-01 UTC next day)
    - cron: '0 0-1 * * *'
  workflow_dispatch:      # manual run button (optional)

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Pushcut
        run: |
          curl --silent --fail --show-error -X POST "$PUSHCUT_URL"
        env:
          PUSHCUT_URL: ${{ secrets.PUSHCUT_URL }}
